var Config = Config || {};

Config.whitelist = [
	// general sites
	'wikipedia\\.org',
	'wikimedia\\.org',
	'wiktionary\\.org',
	'github\\.com',
	'reddit\\.com',
	'gamefaqs\\.com',
	'facebook\\.com',
	'fbcdn\\.net',
	'twitter\\.com',
	'deviantart\\.com',
	'youtube\\.com',
	'youtu\\.be',
	'zombo\\.com',
	'strawpoll\\.me',
	'twitch\\.tv',
	'take-a-screenshot\\.org',
	'myanimelist\\.net',
	'4chan\\.org',
	'tumblr\\.com',

	// pokemon sites
	'pokemonshowdown\\.com',
	'psim\\.us',
	'smogon\\.com',
	'upokecenter\\.com',
	'veekun\\.com',
	'bulbagarden\\.net',
	'serebii\\.net',
	'nuggetbridge\\.com',
	'pokecommunity\\.com',
	'pokemon-online\\.eu',
	'pokemonlab\\.com',
	'shoddybattle\\.com',
	'pokemonxy\\.com',
	'pokemon\\.com',
	'pokecheck\\.org',
	'pokemondb\\.net',
	'pokemoncentral\\.it',
	'poketrade\\.us',

	// personal sites
	'breakdown\\.forumotion\\.com',
	'frostserver\\.net',
	'pokemonmillennium\\.net',
	'thebattletower\\.no-ip\\.org',
	'meltsner\\.com',
	'guangcongluo\\.com',
	'cathyjf\\.com',
	'xiaotai\\.org',

	// rich text
	'docs\\.google\\.com',

	// text
	'pastebin\\.com',
	'hastebin\\.com',
	'trello\\.com',
	'challonge\\.com',
	'piratepad\\.net',

	// music
	'plug\\.dj',

	// images
	'prntscr\\.com',
	'puu\\.sh',
	'd\\.pr',
	'snag\\.gy',
	'gyazo\\.com',
	'imgur\\.com',
	'4cdn\\.org'
];

Config.customcolors = {
	'theimmortal': 'taco',
	'bmelts': 'testmelts',
	'zarel': 'aeo',
	'zarell': 'aeo',
	'greatsage': 'test454',
	'snowflakes': 'snowflake',
	'jumpluff': 'zacchaeus',
	'zacchaeus': 'jumpluff',
	'kraw': 'kraw1',
	'growlithe': 'steamroll',
	'snowflakes': 'endedinariot',
	'doomvendingmachine': 'theimmortal',
	'mikel': 'mikkel',
	'arcticblast': 'rsem',
	'mjb': 'thefourthchaser',
	'thefourthchaser': 'mjb',
	'tfc': 'mjb',
	'mikedecishere': 'mikedec3boobs',
	'heartsonfire': 'haatsuonfaiyaa',
	'royalty': 'wonder9',
	// 'osiris': 'yamraiha',
	'limi': 'azure2',
	'haunter': 'cathy',
	'ginganinja': 'piratesandninjas',
	'aurora': 'c6n6fek',
	'jdarden': 'danielcross',
	'solace': 'amorlan',
	'dcae': 'galvatron',
	'queenofrandoms': 'hahaqor',
	'jelandee': 'thejelandee',
	'diatom': 'dledledlewhooop',
	'waterbomb': 'wb0',
	'texascloverleaf': 'aggronsmash',
	'treecko': 'treecko56',
	'treecko37': 'treecko56',
	'violatic': 'violatic92',
	'exeggutor': 'ironmanatee',
	'ironmanatee': 'exeggutor',
	// 'shamethat': 'aaa10',
	'skylight': 'aerithass',
	// 'prem': 'premisapieceofshit',
	'goddessbriyella': 'princesschelestia',
	'nekonay': 'catbot20',
	'coronis': 'kowonis',
	'vaxter': 'anvaxter',
	'mattl': 'mattl34',
	'shaymin': 'test33',
	// 'orphic': 'dmt6922',
	'kayo': 'endedinariot',
	'tgmd': 'greatmightydoom',
	'vacate': 'vaat111111111',
	'bean': 'dragonbean',
	'yunan': 'osiris13',
	'politoed': 'brosb4hoohs',
	'scotteh': 'nsyncluvr67',
	'bumbadadabum': 'puckerluvr69',
	'yuihirasawa': 'weeabookiller',
	'monohearted': 'nighthearted',
	'prem': 'erinanakiri', // second color change
	'clefairy': 'fuckes',
	'morfent': 'aaaa',
	'nsyncluvr69': 'pinog359',
	'beowulf': '298789z7z',
	'flippy': 'flippo',
	'raoulsteve247': 'raoulbuildingpc',
	'thedeceiver': 'colourtest011',
	'darnell': 'ggggggg',
	'shamethat': 'qpwkfklkjpskllj', // second color change
	'aipom': 'wdsddsdadas',
	'alter': 'spakling',
	'biggie': 'aoedoedad',
	'osiris': 'osiris12', // second color change
	'azumarill': 'azumarill69',
	'redew': 'redeww',
	'sapphire': 'masquerains',
	'calyxium': 'calyxium142',
	'kiracookie': 'kracookie',
	'blitzamirin': 'hikaruhitachii',
	'skitty': 'shckieei',
	'sweep': 'jgjjfgdfg', // second color change
	'val': 'pleasegivemecolorr',
	'valentine': 'pleasegivemecolorr',
	'axew': 'haxorusxi',
	'xzern': 'mintycolors',
	'anto': 'andtalous',
	'shgeldz': 'cactusl00ver',
	'abra': 'lunchawaits',
	'maomiraen': 'aaaaaa',
	'trickster': 'hana',
	'bluekitteh': 'bluekitteh177',
	// 'antemortem': 'abc11092345678',
	'scene': 'aspire',
	'barton': 'hollywood15',
	'royalpains': 'epicwome',
	'zodiax': 'coldeann',
	'ninetynine': 'blackkkk',
	'kasumi': 'scooter4000',
	'xylen': 'bloodyrevengebr',
	'aelita': 'y34co3',
	'faxxifer': 'cm48ubpq',
	'horyzhnz': 'superguy69',
	'quarkz': 'quarkz345',
	'fleurdyleurse': 'calvaryfishes',
	'trinitrotoluene': '4qpr7pc5mb',
	'rekeri': 'qgadlu6g',
	'tailz': 'j',
	'colonialmustang': 'farneo2',
	'peace': 'nxcwrvnf',
	'maisou': {color: '#FF3300'},
	'barandis': {color: '#04DCC3'},
	'yaboimlgshrek': {color: '#75F514'},
	'totoafrica': 'gimmegreen',
	'bloodywolffang': 'purplebisharp',
	'shinyblaziken2000': {color: '#0e127b'},
	'cyllage': {color: '#ffffff'},
	'panpawn': {color: '#ff0066'},
	'vaxza': {color: '#d03c0b'},
	'decision': {color: '#ffd700'},
	'josh': {color: '#8400B2'},
	'articles': {color: '#ff9338'},
	'frage': {color: '#E6E6E6'},
	'ponybot': {color: '#ff5cb6'},
	'blckrbbt': 'drunkenspinda',
	'kupo': 'seke',
	'cathy': {color: '#ff5cb6'},
	'piiiikachuuu': {color: '#FF7D00'},
	'vanitas': {color: '#FF91FF'},
	'terlor': 'sirterlor',
	'chalenged': 'demonicsuccubus',
	'thebestintheworld': 'crowt',
	'hagrus': 'fazehag',
	'papew': 'crowt',
	'mollete': {color: '#0264D4'},
	'hishigan': 'kagunejack',
	'volcun': {color: '#002E8A'},
	'cheeseburger': 'crowt',
	'jayswift': {color: '#0484e1'},
	'chaotic': {color: '#14B7CC'}
};
